---
# tasks file for openldap
- name: Check slapd
  ansible.builtin.stat:
    path: /etc/default/slapd
  register: slapd_exists
  changed_when: false
  tags:
    - openldap
    - check

- name: Configure admin password
  ansible.builtin.debconf:
    name: slapd
    question: 'slapd/password1'
    vtype: 'password'
    value: "{{ openldap_password }}"
  when: not slapd_exists.stat.exists
  tags:
    - openldap
    - debconf
    - password

- name: Confirm admin password
  ansible.builtin.debconf:
    name: 'slapd'
    question: 'slapd/password2'
    vtype: 'password'
    value: "{{ openldap_password }}"
  when: not slapd_exists.stat.exists
  tags:
    - openldap
    - debconf
    - password

- name: Organization name
  ansible.builtin.debconf:
    name: 'slapd'
    question: 'shared/organization'
    vtype: 'string'
    value: "{{ openldap_organization }}"
  when:
    - not slapd_exists.stat.exists
    - openldap_organization is defined
  tags:
    - openldap
    - debconf
    - organization

- name: Domain name
  ansible.builtin.debconf:
    name: 'slapd'
    question: 'slapd/domain'
    vtype: 'string'
    value: "{{ openldap_domain }}"
  when:
    - not slapd_exists.stat.exists
    - openldap_organization is defined
  tags:
    - openldap
    - debconf
    - organization

- name: Packages
  ansible.builtin.package:
    name: "{{ openldap_packages }}"
  tags:
    - openldap
    - packages

- name: Service_facts
  ansible.builtin.service_facts:
  tags:
    - openldap
    - facts

- name: Default configuration
  ansible.builtin.template:
    src: default_slapd.j2
    dest: /etc/default/slapd
    mode: 0644
  when: "'slapd.service' in services"
  notify:
    - Restart slapd
  tags:
    - openldap
    - defaults

# try to configure clients without certificates checking
# - name: "create default organization units"
